### ISSUE TITLE
missing filter on object type while retrieve the instance value?

### ISSUE THREAD

**Issue by mumutu66** [open-hand/devops-service#2]
https://github.com/choerodon/devops-service/blob/c3b16350002891254a52eba00e204260337bea52/src/main/resources/mapper/ApplicationInstanceMapper.xml#L177

since here maybe exist multi object type's like service ingress , why no filter on the object type i.g object = "instance" . on the condition if the object id is equla to some instance id while the type is not `instance` may lead some unexpected behavior?

**Comment by zhuzhiyang** [comment]
Because the role of this sql is to query the values of the instance deployment, create service and inress is not associated with values

**Comment by zhuzhiyang** [comment]
You are right, this sql will cause a bug, we will fix it in the next version, thank you for your suggestion!
