### ISSUE TITLE
对象声明变量命名容易引起歧义

### ISSUE THREAD

**Issue by coolintan** [open-hand/devops-service#5]
https://github.com/choerodon/devops-service/blob/f820619f39e15131cb9e8c5807e1c1c6fa004043/src/main/java/io/choerodon/devops/app/service/impl/ApplicationServiceImpl.java#L280

声明对象时, 对象名称和对象不一致,容易引起歧义. 希望改成
![image](https://user-images.githubusercontent.com/6115335/54403641-bcd81180-470b-11e9-9995-988ca7382a1f.png)

**Comment by cczhung** [comment]
谢谢反馈
