### ISSUE TITLE
Gitlab开发者权限应该配置成30, 而不是40

### ISSUE THREAD

**Issue by coolintan** [open-hand/devops-service#6]
https://github.com/choerodon/devops-service/blob/55d442251790d17361b3e5a6e08dffd15b080781/src/main/java/io/choerodon/devops/app/service/impl/GitlabGroupMemberServiceImpl.java#L218

**Comment by coolintan** [comment]
没人反馈吗?

**Comment by zhuzhiyang** [comment]
您好，这边目前对于gitlab开发者权限是分为2部分的，一部分是应用代码库的权限，是对应的30，  另外一部分是环境gitops库的权限，由于我们gitops需要去gitlab库创文件，需要40的权限。
