### ISSUE TITLE
删除失效环境应删除的gitops相关数据

### ISSUE THREAD

**Issue by carllhw** [open-hand/devops-service#7]
https://github.com/choerodon/devops-service/blob/3d4b0aa695ee1e05bc562fe1edb0f69b75201416/src/main/java/io/choerodon/devops/app/service/impl/DevopsEnvironmentServiceImpl.java#L678

例如

- 克隆下来的代码库，如果涉及到多个pod的话还需要保证一致删除。或者克隆目录为`环境代码-环境ID`
- 保存的push记录，`devops_env_commit`
- 等等

**Comment by cczhung** [comment]
谢谢反馈，会在0.16版本进行修复
