### ISSUE TITLE
通过inputStream流 替换文件的参数会导致模板里的图片经过渲染不可用

### ISSUE THREAD

**Issue by carllhw** [open-hand/devops-service#8]
https://github.com/choerodon/devops-service/blob/9f4aaa0783cc298fc76b949d31c17a3aea46ddb2/src/main/java/io/choerodon/devops/infra/common/util/FileUtil.java#L91

模板图片文件：http://git.alpha.saas.hand-china.com/hscf_template/web/blob/master/src/page/index/logo.png

渲染后的文件：http://git.alpha.saas.hand-china.com/hscf-hscf-hjl/demo7-web/blob/master/src/page/index/logo.png

**Comment by carllhw** [comment]
https://github.com/choerodon/devops-service/blob/9f4aaa0783cc298fc76b949d31c17a3aea46ddb2/src/main/java/io/choerodon/devops/infra/common/util/FileUtil.java#L77

还有为啥一定要加一个换行符？

可能是因为加了这个字符导致渲染图片失败

**Comment by carllhw** [comment]
@cczhung

**Comment by cczhung** [comment]
这里扫描是用来替换部分系统所需的变量，但是这里没有对文件类型进行筛选，会在新版本中进行修复，谢谢反馈

**Comment by carllhw** [comment]
建议不要添加换行符

由于前端代码的ESLint检查会检查文件末尾的换行符数量，超过1个或没有都会报错，这样模板里的js文件末尾有一个的话，渲染后就有两个，导致启动不了。这样就模板库可以启动，但是渲染后的应用由于eslint检查启动不了

**Comment by cczhung** [comment]
0.16.0版本已修复该问题
